// Product flow and input-boundary checks in JSDOM, with a simulated native bridge.
// No GitHub submission, Android device, layout or kitchen validation occurs here.
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.join(__dirname,'../web'),windows=[];
function boot(storage={}){
 const dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://cookdaily.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document;windows.push(w);
 const errors=[],external=[],copies=[],exports=[];w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.HTMLDialogElement.prototype.showModal=function(){this.__opener=d.activeElement;this.open=true;this.querySelector('button,input,textarea,select,a[href]')?.focus();};w.HTMLDialogElement.prototype.close=function(){this.open=false;if(this.__opener?.isConnected)this.__opener.focus();};
 w.addEventListener('error',e=>errors.push(e.message));
 w.Kitchen={timerStatus:()=>JSON.stringify({exact:true,notifications:true}),startTimer:()=> 'native',cancelTimer:()=>{},cooking:()=>{},appearance:()=>{},systemDark:()=>false,landscape:()=>{},openExternal:(url,choose)=>external.push({url,choose}),notificationSettings:()=>{},exactSettings:()=>{},copyText:text=>{copies.push(text);return true;},shareText:()=>true,exportBackup:text=>exports.push(text),importBackup:()=>{}};
 for(const [k,v] of Object.entries(storage))w.localStorage.setItem(k,v);for(const f of ['recipes.js','search-index.js','core.js','app.js'])w.eval(fs.readFileSync(path.join(base,f),'utf8'));
 const q=s=>d.querySelector(s),click=s=>{const e=q(s);assert.ok(e,s);e.focus();e.click();},input=(s,value,type='input')=>{const e=q(s);assert.ok(e,s);e.focus();e.value=value;e.dispatchEvent(new w.Event(type,{bubbles:true}));},page=p=>{w.history.replaceState(null,'','#'+p);w.dispatchEvent(new w.HashChangeEvent('hashchange'));};
 const stored=k=>JSON.parse(w.localStorage.getItem('cook-'+k)),snapshot=()=>Object.fromEntries(Array.from({length:w.localStorage.length},(_,n)=>{const k=w.localStorage.key(n);return [k,w.localStorage.getItem(k)];}));
 return {w,d,q,click,input,page,stored,snapshot,errors,external,copies,exports};
}
const tick=()=>new Promise(r=>setTimeout(r,0));
function legacyBackup(a,schema=3){return JSON.stringify({app:'cookdaily',schema,data:{saved:['d01'],basket:['d01'],bought:{},prefs:{category:'家常菜',portions:2},recent:[],history:[],theme:'dark',notes:{d01:{text:'旧备份笔记',updatedAt:1}},progress:{d01:{index:1,checked:[0],updatedAt:1,revision:a.w.RECIPES.find(r=>r.id==='d01').revision}},linkMode:'default'}});}
(async()=>{try{
 const browse=boot({'cook-prefs':JSON.stringify({category:'早餐',max:15,noSpicy:true,exclude:'花生',difficulty:3,noNoodles:true,group:'面条粉类',query:'不存在的菜'})});
 assert.ok(browse.q('[data-browse]'));assert.ok(browse.q('[data-browse]').compareDocumentPosition(browse.q('.random-box'))&4);browse.click('[data-browse]');await tick();assert.equal(browse.w.location.hash,'#recipes');
 const prefs=browse.stored('prefs');for(const k of ['category','group','cuisine','query'])assert.equal(prefs[k],'');assert.equal(prefs.max,0);assert.equal(prefs.difficulty,0);assert.equal(prefs.noNoodles,false);assert.equal(prefs.noSpicy,true);assert.equal(prefs.exclude,'花生');assert.ok(browse.q('.card-open'));

 const fuzzy=boot();fuzzy.page('recipes');fuzzy.click('[data-reset-filters]');fuzzy.input('#search','麻辣豆腐');assert.equal(fuzzy.q('.recipe-card'),null);const candidate=fuzzy.q('#main [data-open="d57"]');assert.ok(candidate,'Mapo tofu is a suggestion for the imprecise query');candidate.focus();candidate.click();assert.equal(fuzzy.q('#recipe-dialog').open,true);assert.equal(fuzzy.q('#search').value,'麻辣豆腐');assert.equal(fuzzy.stored('prefs').query,'麻辣豆腐');fuzzy.w.appBack();fuzzy.page('home');assert.equal(fuzzy.q('#selection-controls [data-draw]').disabled,true);assert.equal(fuzzy.q('#random-result .random-result'),null);
 fuzzy.page('recipes');fuzzy.input('#search','麻婆豆腐');assert.ok(fuzzy.q('.recipe-card [data-open="d57"]'));assert.ok(fuzzy.q('.search-suggestions [data-open]'),'close suggestions remain visible alongside strict results');assert.equal(fuzzy.q('.search-suggestions [data-open="d57"]'),null,'strict dish is not repeated in suggestions');fuzzy.input('#search','麻辣豆腐');fuzzy.input('#exclude','大豆');assert.equal(fuzzy.q('#main [data-open="d57"]'),null);fuzzy.input('#exclude','');fuzzy.q('#no-spicy').checked=true;fuzzy.q('#no-spicy').dispatchEvent(new fuzzy.w.Event('change',{bubbles:true}));assert.equal(fuzzy.q('#main [data-open="d57"]'),null);fuzzy.q('#no-spicy').checked=false;fuzzy.q('#no-spicy').dispatchEvent(new fuzzy.w.Event('change',{bubbles:true}));fuzzy.input('#max','15','change');assert.equal(fuzzy.q('#main [data-open="d57"]'),null);
 fuzzy.input('#search','<img src=x onerror=alert(1)>');fuzzy.click('[data-category="早餐"]');assert.equal(fuzzy.q('#main img[src="x"]'),null);assert.equal(fuzzy.q('#main [onerror]'),null);assert.ok(fuzzy.q('#main [data-request-open]'));
 const favorites=boot({'cook-saved':'["d57"]'});favorites.page('favorites');favorites.input('#search','麻辣豆腐');assert.ok(favorites.q('#main [data-open="d57"]'),'favorites zero strict results still show its own close match');assert.ok([...favorites.d.querySelectorAll('#main [data-open]')].every(e=>e.dataset.open==='d57'),'favorites suggestions cannot escape the saved collection');favorites.input('#exclude','大豆');assert.equal(favorites.q('#main [data-open="d57"]'),null);

 const local=boot();Object.defineProperty(local.w.navigator,'onLine',{value:false,configurable:true});local.click('[data-request-open]');assert.equal(local.q('#requests-dialog').open,true);assert.equal(local.q('#request-name').maxLength,40);assert.equal(local.q('#request-note').maxLength,300);
 const name='<img src=x onerror=alert(1)>菜',note='"<&> 只是做法建议';local.input('#request-name',name);local.input('#request-note',note);local.click('[data-request-save]');assert.equal(local.stored('requests').length,1);assert.equal(local.stored('requests')[0].name,name);assert.ok(local.q('#requests-dialog').textContent.includes(name));assert.equal(local.q('#requests-dialog [onerror]'),null);assert.equal(local.q('#requests-dialog img[src="x"]'),null);
 local.input('#request-name',' '+name+' ');local.input('#request-note',note);local.click('[data-request-save]');assert.equal(local.stored('requests').length,1,'duplicate save must not append another record');
 const beforeSubmit=local.w.localStorage.getItem('cook-requests');local.click('[data-request-submit="0"]');assert.equal(local.external.length,1);const draft=new URL(local.external[0].url);assert.equal(draft.origin,'https://github.com');assert.equal(draft.pathname,'/leijiangjiang547-arch/jintian-chi-shenme/issues/new');assert.equal(local.w.localStorage.getItem('cook-requests'),beforeSubmit);assert.doesNotMatch(local.q('#requests-dialog').textContent,/已提交|已发送/);assert.match(local.q('#requests-dialog').textContent,/公开/);assert.match(local.q('#requests-dialog').textContent,/登录/);
 local.click('[data-request-copy="0"]');await tick();assert.equal(local.copies.length,1);assert.ok(local.copies[0].includes(name)&&local.copies[0].includes(note));local.w.Kitchen.copyText=()=>false;local.click('[data-request-copy="0"]');await tick();const textDialog=[...local.d.querySelectorAll('dialog[open]')].find(el=>el.querySelector('textarea[readonly]'));assert.ok(textDialog,'native copy failure has a readable fallback');assert.ok(textDialog.querySelector('textarea[readonly]').value.includes(name));assert.doesNotMatch(textDialog.querySelector('.dialog-header')?.textContent||'',/买菜清单/);assert.equal(local.w.appBack(),true);assert.equal(local.q('#requests-dialog').open,true);
 local.w.appBack();local.click('#settings');local.click('[data-export]');const exported=JSON.parse(local.exports[0]);assert.equal(exported.schema,4);assert.equal(exported.data.requests.length,1);local.w.receiveBackup(legacyBackup(local,3));assert.equal(local.stored('requests').length,1);assert.equal(local.stored('requests')[0].name,name);assert.deepEqual(local.stored('saved'),['d01']);assert.equal(local.stored('notes').d01.text,'旧备份笔记');assert.equal(local.stored('progress').d01.index,1);
 for(const schema of [1,2]){local.w.receiveBackup(legacyBackup(local,schema));assert.equal(local.stored('requests').length,1,'legacy restore preserves queued requests');}
 const restored=boot(local.snapshot());restored.click('[data-request-open]');assert.ok(restored.q('#requests-dialog').textContent.includes(name));restored.click('[data-request-remove="0"]');assert.deepEqual(restored.stored('requests'),[]);

 const readOnly=boot({'cook-version':'999','cook-requests':JSON.stringify([{name:'已存菜',note:'',at:Date.now()}])});readOnly.click('[data-request-open]');readOnly.input('#request-name','不应保存的菜');readOnly.input('#request-note','存储保护');readOnly.click('[data-request-save]');assert.equal(readOnly.stored('requests').length,1);assert.doesNotMatch(readOnly.q('#requests-dialog .local-toast')?.textContent||'',/已保存|已记下/);assert.match(readOnly.q('#requests-dialog .local-toast')?.textContent||'',/更新版本|存储/);
 const outage=boot();outage.click('[data-request-open]');outage.w.Storage.prototype.setItem=function(){throw new Error('QuotaExceededError');};outage.input('#request-name','写入失败测试菜');outage.click('[data-request-save]');assert.ok(!outage.stored('requests')?.some(r=>r.name==='写入失败测试菜'));assert.doesNotMatch(outage.q('#requests-dialog .local-toast')?.textContent||'',/已保存|已记下/);assert.match(outage.q('#requests-dialog .local-toast')?.textContent||'',/存储/);assert.equal(outage.q('[data-request-submit]'),null,'failed save must not become a supposedly stored entry');
 const nested=boot();nested.click('#settings');nested.click('#settings-content [data-request-open]');nested.input('#request-name','嵌套层提示测试菜');nested.click('[data-request-save]');assert.match(nested.q('#requests-dialog .local-toast')?.textContent||'',/已保存|已保存在/,'save result is visible in the top request dialog');assert.ok(nested.q('#requests-dialog').contains(nested.d.activeElement),'request rerender retains focus inside its dialog');
 for(const app of [browse,fuzzy,favorites,local,restored,readOnly,outage,nested])assert.deepEqual(app.errors,[]);
 console.log('v0.9 DOM passed: prominent browse retains restrictions, non-mutating filter-bound fuzzy hints, offline escaped/deduplicated requests, public issue draft and copy fallback, schema4/legacy persistence and storage-failure accuracy. Native bridge simulated.');
}finally{for(const w of windows)w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
