// Simulated bridge/DOM integration; this is not Android device or kitchen validation.
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.join(__dirname,'../web'),windows=[];
function boot(storage={},status={exact:true,notifications:true},bridge=true){
 const dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://cookdaily.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document;windows.push(w);const errors=[],copies=[],shares=[];let starts=0;
 w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.addEventListener('error',e=>errors.push(e.message));
 if(bridge)w.Kitchen={timerStatus:()=>JSON.stringify(status),startTimer:()=>{starts++;return status.exact&&status.notifications?'native':'foreground';},cancelTimer:()=>{},cooking:()=>{},appearance:()=>{},systemDark:()=>false,landscape:()=>{},openExternal:()=>{},notificationSettings:()=>{},exactSettings:()=>{},copyText:text=>{copies.push(text);return true;},shareText:text=>{shares.push(text);return true;}};
 for(const [k,v] of Object.entries(storage))w.localStorage.setItem(k,v);for(const f of ['recipes.js','search-index.js','core.js','app.js'])w.eval(fs.readFileSync(path.join(base,f),'utf8'));
 const q=s=>d.querySelector(s),click=s=>{const e=q(s);assert.ok(e,s);e.focus();e.click();},change=(s,v,type='change')=>{const e=q(s);assert.ok(e,s);e.focus();if(typeof v==='boolean')e.checked=v;else e.value=v;e.dispatchEvent(new w.Event(type,{bubbles:true}));},page=p=>{w.history.replaceState(null,'','#'+p);w.dispatchEvent(new w.HashChangeEvent('hashchange'));};
 const snapshot=()=>Object.fromEntries(Array.from({length:w.localStorage.length},(_,i)=>{const k=w.localStorage.key(i);return [k,w.localStorage.getItem(k)];}));
 const open=id=>{page('recipes');click('[data-reset-filters]');change('#search',w.RECIPES.find(r=>r.id===id).name,'input');click('[data-open="'+id+'"]');};return {w,d,q,click,change,page,snapshot,open,errors,copies,shares,status,get starts(){return starts;}};
}
(async()=>{try{
 const a=boot({'cook-recent':'["d01"]','cook-history':JSON.stringify([{id:'d10',at:Date.now()}])});a.w.Math.random=()=>0;a.click('[data-draw]');assert.notEqual(a.w.RECIPES.find(r=>r.id===a.q('#random-result [data-open]').dataset.open).group,a.w.RECIPES.find(r=>r.id==='d01').group);
 const first=a.q('#random-result [data-open]').dataset.open;a.click('#random-result [data-redraw]');assert.notEqual(a.q('#random-result [data-open]').dataset.open,first);assert.ok(a.d.activeElement.hasAttribute('data-redraw'));
 const previous=a.q('#random-result [data-open]').dataset.open;a.change('#search','无此菜XYZ','input');assert.equal(a.q('#random-result [data-open]').dataset.open,previous);assert.equal(a.q('#random-result .random-result'),null);assert.ok(a.q('.previous-result'));assert.equal(a.q('#selection-controls [data-draw]').disabled,true);
 a.change('#search','红烧肉','input');assert.equal(a.q('#random-result [data-open]').dataset.open,previous);a.click('#random-result [data-redraw]');assert.ok(a.q('#random-result').textContent.includes('红烧肉'));
 a.open('d01');assert.equal(a.q('.tutorial-panel').tagName,'DETAILS');assert.equal(a.q('.tutorial-panel').open,false);assert.ok(a.q('.tutorial-panel').compareDocumentPosition(a.q('.ingredients'))&4);assert.equal(a.q('#recipe-dialog figcaption'),null);a.q('.tutorial-panel').open=true;a.q('.tutorial-panel').dispatchEvent(new a.w.Event('toggle'));a.change('[data-done="0"]',true);assert.equal(a.d.activeElement.dataset.done,'0');assert.equal(a.q('.tutorial-panel').open,true);
 const timerIndex=a.w.RECIPES.find(r=>r.id==='d01').steps.findIndex(s=>s.seconds);a.click('[data-timer="'+timerIndex+'"]');const stop=a.q('[data-stop-timer]');stop.focus();a.w.nativeResume();assert.equal(a.q('[data-stop-timer]'),stop);assert.equal(a.d.activeElement,stop);assert.equal(a.q('#timer-permission-dialog').open,false);
 a.click('[data-close]');a.page('home');a.click('[data-category="早餐"]');assert.equal(a.d.activeElement.dataset.category,'早餐');
 const b=boot({'cook-basket':'["d01","d02","v7b60"]'});b.page('shopping');assert.doesNotMatch(b.q('.shopping-items').textContent,/饮用水/);b.change('[data-bought="鸡蛋|个"]',true);b.click('[data-copy-shopping]');await Promise.resolve();assert.equal(b.copies.length,1);assert.doesNotMatch(b.copies[0],/□ 鸡蛋|□ 饮用水/);b.change('#shopping-pending',false);b.click('[data-share-shopping]');assert.match(b.shares[0],/已购买\n✓ 鸡蛋/);
 b.click('[data-portions="1"]');assert.equal(b.q('[data-bought="鸡蛋|个"]').checked,false);assert.ok(b.q('.amount-changed'));b.change('[data-bought="鸡蛋|个"]',true);assert.equal(b.q('[data-bought="鸡蛋|个"]').closest('label').querySelector('small'),null);
 const c=boot({}, {exact:false,notifications:false});c.open('d01');c.click('[data-timer="'+timerIndex+'"]');assert.equal(c.starts,1);assert.equal(c.q('#timer-permission-dialog').open,true);assert.match(c.q('#timer-hint-text').textContent,/已开始.*重新开始/);assert.equal(c.w.appBack(),true);assert.equal(c.q('#timer-permission-dialog').open,false);c.click('[data-timer="'+timerIndex+'"]');assert.equal(c.q('#timer-permission-dialog').open,false);
 const resumed=boot(c.snapshot(),{exact:false,notifications:true});resumed.open('d01');resumed.click('[data-timer="'+timerIndex+'"]');assert.equal(resumed.q('#timer-permission-dialog').open,false);
 const firstHint=boot({}, {exact:false,notifications:true});firstHint.open('d01');firstHint.click('[data-timer="'+timerIndex+'"]');firstHint.click('[data-timer-settings]');assert.equal(firstHint.q('#settings-dialog').open,true);assert.equal(firstHint.q('#timer-permission-dialog').open,false);assert.match(firstHint.q('#settings-content').textContent,/重新开始步骤计时/);
 const fallback=boot({'cook-basket':'["d01"]'},undefined,false);fallback.page('shopping');fallback.click('[data-share-shopping]');assert.equal(fallback.q('#shopping-export-dialog').open,true);assert.match(fallback.q('#shopping-export-text').value,/买菜清单/);assert.equal(fallback.w.appBack(),true);assert.equal(fallback.q('#shopping-export-dialog').open,false);
 const rejected=boot({'cook-basket':'["d01"]'});rejected.w.Kitchen.copyText=()=>false;rejected.page('shopping');rejected.click('[data-copy-shopping]');assert.equal(rejected.q('#shopping-export-dialog').open,true);rejected.w.appBack();rejected.w.Kitchen.shareText=()=>false;rejected.click('[data-share-shopping]');assert.equal(rejected.q('#shopping-export-dialog').open,true);
 const readOnly=boot({'cook-version':'999'});readOnly.open('d01');readOnly.change('#recipe-note','不会实际保存','input');readOnly.click('[data-journal-save]');assert.equal(readOnly.w.localStorage.getItem('cook-notes'),null);assert.match(readOnly.q('#recipe-dialog .local-toast').textContent,/更新版本/);readOnly.click('[data-add="d01"]');assert.equal(readOnly.w.localStorage.getItem('cook-basket'),null);assert.doesNotMatch(readOnly.q('#recipe-dialog .local-toast').textContent,/已加入/);
 b.w.nativeMessage('全局提示');assert.ok(b.q('#toast').classList.contains('visible'));b.open('d01');b.w.nativeMessage('详情提示');assert.ok(b.q('#recipe-dialog .local-toast').classList.contains('visible'));assert.equal(b.q('#toast').classList.contains('visible'),false);
 for(const app of [a,b,c,resumed,firstHint,fallback,rejected,readOnly])assert.deepEqual(app.errors,[]);
 console.log('v0.8 DOM passed: redraw/no-auto-selection, compact zero-result state, folded early tutorials, focus retention, stable timer nodes, pending/full shopping copy/share, changed quantity checks, one-time timer help and back-safe text fallback. Bridge simulated.');
}finally{for(const w of windows)w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
