(() => {
 'use strict';
 const R=window.RECIPES,C=window.CookCore,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem('cook-'+k))??f;}catch{return f;}};
 const write=(k,v)=>{try{localStorage.setItem('cook-'+k,JSON.stringify(v));}catch{toast('本机存储不可用，本次操作仅在当前页面保留');}};
 const ids=x=>Array.isArray(x)?x.filter(id=>R.some(r=>r.id===id)):[];
 let saved=ids(read('saved',[])),basket=ids(read('basket',[])),bought=read('bought',{}),prefs=read('prefs',{});
 if(!prefs||typeof prefs!=='object'||Array.isArray(prefs))prefs={};if(!bought||typeof bought!=='object')bought={};
 let portions=Math.max(1,Math.min(6,Number(prefs.portions)||2)),category=prefs.category==='早餐'?'早餐':'家常菜',max=[15,20,30,45].includes(Number(prefs.max))?Number(prefs.max):0,noSpicy=!!prefs.noSpicy,exclude=typeof prefs.exclude==='string'?prefs.exclude:'',query='',listCategory='',page='home',selected=null,recent=ids(read('recent',[])),detail=null,cooking=false,cookIndex=0,done={};
 let group='',cuisine='',difficulty=[1,2,3].includes(Number(prefs.difficulty))?Number(prefs.difficulty):0,noNoodles=false;
 const difficultyLabels={1:'轻松做',2:'日常做',3:'挑战做'};
 const cuisineOrder=['川菜','湘菜','鲁菜','粤菜','苏菜','浙菜','闽菜','徽菜','津菜','东北风味','家常风味'];
 let timer=read('timer',null),toastHandle,audioContext;
 if(timer&&(!R.some(r=>r.id===timer.recipe)||!Number.isFinite(timer.end)))timer=null;
 function persist(){write('prefs',{portions,category,max,noSpicy,exclude,difficulty});}
 function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastHandle);toastHandle=setTimeout(()=>el.classList.remove('visible'),3000);}
 const amt=i=>C.format(i.amount)+' '+({g:'克',ml:'毫升'}[i.unit]||i.unit);
 const total=R.length,breakfastCount=R.filter(r=>r.category==='早餐').length,homeCount=total-breakfastCount;
 const ingredientText=r=>C.scale(r,portions).filter(i=>i.amount>0).map(i=>i.name+' '+amt(i)).join(' · ');
 const tones=['#ece9d9','#eee2d3','#e6ebdc','#f1e7d7','#e6e8e0'];
 function card(r,n=0){return `<article class="recipe-card"><button class="card-open" data-open="${r.id}" aria-label="查看${r.name}菜谱"><div class="card-visual" style="--tone:${tones[n%tones.length]}"><span class="badge">${r.group||r.category}</span><span class="emoji" aria-hidden="true">${r.emoji}</span></div><div class="card-body"><h3>${r.name}</h3><p>${difficultyLabels[r.difficulty]} · ${r.minutes} 分钟 · ${r.ingredients.filter(i=>i.amount>0).slice(0,2).map(i=>i.name).join(' / ')}</p></div></button><button class="save-btn ${saved.includes(r.id)?'saved':''}" data-save="${r.id}" aria-label="${saved.includes(r.id)?'取消收藏':'收藏'}${r.name}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'♥':'♡'}</button></article>`;}
 function serving(){return `<div class="serving"><span>用餐人数</span><button data-portions="-1" aria-label="减少人数" ${portions===1?'disabled':''}>−</button><strong>${portions} 人</strong><button data-portions="1" aria-label="增加人数" ${portions===6?'disabled':''}>+</button></div>`;}
 function filters(all=false){return `<div class="segmented" aria-label="菜谱类别">${(all?['','家常菜','早餐']:['家常菜','早餐']).map(c=>`<button data-category="${c}" class="${(all?listCategory:category)===c?'active':''}" aria-pressed="${(all?listCategory:category)===c}">${c||'全部'}${c==='家常菜'?' · '+homeCount:c==='早餐'?' · '+breakfastCount:''}</button>`).join('')}</div>`;}
 function modes(){return `<div class="difficulty-picker" aria-label="按做菜难度筛选">${[[0,'全部难度','随心选择'],[1,'轻松做','基础操作'],[2,'日常做','练练火候'],[3,'挑战做','多些技巧']].map(([n,t,sub])=>`<button data-difficulty="${n}" class="${difficulty===n?'active':''}" aria-pressed="${difficulty===n}"><strong>${t}</strong><small>${sub}</small></button>`).join('')}</div><p class="difficulty-hint">难度看操作，用时单独选。慢炖也可以很简单。</p>`;}
 function variety(){const cat=page==='home'?category:listCategory;const groups=[...new Set(R.filter(r=>!cat||r.category===cat).map(r=>r.group))];return `${modes()}<div class="variety-controls">${cat!=='早餐'?`<label>想吃哪地 <select id="cuisine" aria-label="菜系"><option value="">全部菜系</option>${cuisineOrder.filter(c=>R.some(r=>r.cuisine===c)).map(c=>`<option value="${c}" ${cuisine===c?'selected':''}>${c}${c==='鲁菜'?'（山东）':''}</option>`).join('')}</select></label>`:''}<label>想吃哪种 <select id="food-group" aria-label="菜品种类"><option value="">各种都试试</option>${groups.map(g=>`<option value="${esc(g)}" ${group===g?'selected':''}>${g}</option>`).join('')}</select></label><label><input id="no-noodles" type="checkbox" ${noNoodles?'checked':''}>这次不吃面条粉类</label><button class="text-btn" data-reset-filters>重置筛选</button></div>`;}
 function options(){return `<div class="controls"><label>预计用时 <select id="max" aria-label="最长用时">${[[0,'不限'],[15,'15分钟内'],[20,'20分钟内'],[30,'30分钟内'],[45,'45分钟内']].map(([v,t])=>`<option value="${v}" ${max===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="toggle"><input id="no-spicy" type="checkbox" ${noSpicy?'checked':''}>不吃辣</label></div><input id="exclude" class="exclude" aria-label="排除食材" placeholder="不想吃的食材，如：香菜、牛肉" value="${esc(exclude)}">`;}
 const pool=()=>C.filter(R,{category:page==='home'?category:listCategory,max,noSpicy,exclude,query:page==='home'?'':query,group,cuisine,difficulty,noNoodles});
 function empty(title,text){return `<div class="empty"><div class="big">🥣</div><h3>${title}</h3><p>${text}</p></div>`;}
 function home(){const shortlist=pool();if(!selected||!shortlist.some(r=>r.id===selected.id))selected=shortlist[0]||null;return `<section class="hero"><div class="hero-copy"><div class="eyebrow">A LITTLE INSPIRATION, EVERY DAY</div><h1>今天的饭，<br>让<em>一点随机</em>决定。</h1><p>从简单早餐，到热乎家常菜。<br>备好食材，一步一步做。</p><button class="primary" data-draw>✦ 帮我选一道</button><div style="margin-top:15px"><span class="pill">${total} 道量化菜谱 · 离线也能看</span></div></div><img class="hero-art" src="plate.svg" alt="一盘番茄炒蛋插画"></section><div class="section-head"><h2>把纠结，交给这一刻</h2><span class="subtle">先换种类，再选一道</span></div><section class="random-box"><div class="random-top">${filters()}<span class="subtle">避开近期菜品，优先换种类</span></div>${options()}${variety()}<div id="random-result">${result()}</div></section><div class="section-head"><h2>每餐都有好选择</h2><a class="text-btn" href="#recipes">查看全部 →</a></div><div class="recipe-grid">${['d88','d92','d93','d95','d98','d99'].map(id=>R.find(r=>r.id===id)).filter(Boolean).map(card).join('')}</div><div class="tips-strip"><span>用量说清楚</span><span>火候有参照</span><span>每一步都踏实</span></div><p class="footer-note">家庭量化改编 · 插画为示意 · 菜谱尚未逐道试做<br>试做时先核对食材和调料，计时结束后仍须检查熟透。</p>`;}
 function result(){return selected?`<div class="random-result" aria-live="polite"><div class="result-art">${selected.emoji}</div><div><span class="eyebrow">今天就做这道</span><h3>${selected.name}</h3><div class="meta"><span>◷ ${selected.minutes} 分钟</span><span>${selected.cuisine}</span><span>${difficultyLabels[selected.difficulty]}</span><span>${selected.group}</span><span>${selected.spicy?'有辣':'不辣'}</span><span>${pool().length} 道符合条件</span></div></div><div class="result-actions"><button class="secondary" data-draw>↻ 换一道</button><button class="primary" data-open="${selected.id}">看做法 →</button></div></div>`:empty('暂时没有符合条件的菜','试着更换菜系或难度，放宽用时，或减少排除食材。');}
 function listing(){const list=page==='favorites'?pool().filter(r=>saved.includes(r.id)):pool();return `<div class="eyebrow">${page==='favorites'?'YOUR LITTLE COLLECTION':'THE EVERYDAY COOKBOOK'}</div><h1 class="page-title">${page==='favorites'?'想吃的，先收藏':'好好吃饭，每天有新意'}</h1><p class="subtle">${page==='favorites'?'把喜欢的味道，留给下一顿。':`${homeCount} 道家常菜 · ${breakfastCount} 道早餐 · 每一道都有明确步骤`}</p><input class="search" id="search" value="${esc(query)}" placeholder="搜索菜名，或冰箱里的食材" aria-label="搜索菜名或食材"><div class="filters">${filters(true)}${options()}${variety()}</div><div id="list-results"><p class="count">共 ${list.length} 道 · 用时含常规备菜，受熟练度影响</p>${list.length?`<div class="recipe-grid">${list.map(card).join('')}</div>`:empty(page==='favorites'?'还没有符合条件的收藏':'没有找到这道菜','点菜谱右上角的心，或试着调整筛选条件。')}</div>`;}
 function shopping(){const list=C.shopping(R,basket,portions);return `<div class="eyebrow">BEFORE YOU COOK</div><h1 class="page-title">买齐这一餐</h1><p class="subtle">同名同单位的食材已合并；清水不列入采购。</p>${serving()}<section>${basket.map(id=>{const r=R.find(x=>x.id===id);return `<div class="shop-recipe"><span>${r.emoji}</span><button class="text-btn name" data-open="${r.id}">${r.name}</button><button class="text-btn" data-remove="${id}" aria-label="从清单移除${r.name}">移除</button></div>`;}).join('')}</section><div style="margin-top:22px">${list.length?list.filter(i=>!i.name.includes('水')).map(i=>`<label class="shop-item ${bought[i.key]?'checked':''}"><input type="checkbox" data-bought="${esc(i.key)}" ${bought[i.key]?'checked':''}><span>${i.name}</span><strong>${amt(i)}</strong></label>`).join(''):empty('清单还是空的','在菜谱里点击“加入买菜清单”，一餐所需一目了然。')}</div>${basket.length?'<p class="footer-note">勾选状态只保存在本机。改变人数、增删菜谱后会重置勾选，避免漏买。</p>':''}`;}
 function render(){document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));$('#main').innerHTML=page==='home'?home():page==='shopping'?shopping():listing();}
 function updateList(){if(page==='home'){const p=pool();if(selected&&!p.some(r=>r.id===selected.id))selected=null;if(!selected)selected=p[0]||null;$('#random-result').innerHTML=result();}else if(page==='recipes'||page==='favorites'){const list=page==='favorites'?pool().filter(r=>saved.includes(r.id)):pool();$('#list-results').innerHTML=`<p class="count">共 ${list.length} 道 · 用时含常规备菜，受熟练度影响</p>${list.length?`<div class="recipe-grid">${list.map(card).join('')}</div>`:empty('没有符合条件的菜谱','试着调整筛选条件。')}`;}}
 function sourceHtml(r){return `<h2>教程与来源</h2><div class="sources">${r.sources.map(s=>`<a href="${esc(s.url)}">${esc(s.title)} ↗</a><small>${esc(s.note||(s.kind==='recipe'?'对应菜谱，已做家庭量化改编':'相关烹饪技法参考；不是本配方原文'))}</small>`).join('')}${r.videos.map(v=>`<a href="${esc(v.url)}">▷ ${esc(v.title)} ↗</a><small>${esc(v.status)}</small>`).join('')}<h3 style="font-size:14px;margin-top:23px">去平台搜索更多教程</h3><small>以下是搜索入口，不是已核验的具体视频。平台可能要求登录。</small><div class="video-search"><a href="https://search.bilibili.com/all?keyword=${encodeURIComponent(r.name+' 家常做法')}">B站搜索 ↗</a><a href="https://www.douyin.com/search/${encodeURIComponent(r.name+' 做法')}">抖音搜索 ↗</a></div></div>`;}
 function stepHtml(s,i){return `<section class="step ${done[detail.id+'-'+i]?'done':''}"><div class="step-top"><span class="step-num">${String(i+1).padStart(2,'0')}</span><h3>${s.title}</h3><small>${s.heat}</small></div><p>${esc(C.stepText(s.text,portions,2,detail))}</p><div class="check-note">做对的标志：${esc(C.stepText(s.check,portions,2,detail))}</div>${s.seconds?`<button class="timer-btn" data-timer="${i}">◷ 计时 ${C.duration(s.seconds)}</button>`:''}<label class="step-check"><input type="checkbox" data-done="${i}" ${done[detail.id+'-'+i]?'checked':''}>这一步做好了</label></section>`;}
 function detailRender(){if(!detail)return;const r=detail;const dlg=$('#recipe-dialog');dlg.innerHTML=`<div class="dialog-header"><button class="icon-btn" data-close aria-label="${cooking?'返回菜谱':'关闭菜谱'}">${cooking?'‹':'×'}</button><strong>${cooking?'跟着做 · '+(cookIndex+1)+' / '+r.steps.length:'把这道菜做好'}</strong><button class="icon-btn" data-save="${r.id}" aria-label="${saved.includes(r.id)?'取消收藏':'收藏'}${r.name}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'♥':'♡'}</button></div><div class="detail">${cooking?cookHtml():`<div class="detail-title"><div class="food">${r.emoji}</div><div><h1>${r.name}</h1><div class="meta"><span>◷ 约 ${r.minutes} 分钟</span><span>${r.spicy?'有辣':'不辣'}</span><span>${r.cuisine}</span><span>${difficultyLabels[r.difficulty]}</span></div></div></div><p class="note">${esc(r.difficultyReason)}</p>${serving()}<p class="note" style="margin-top:17px">用量已换算为 ${portions} 人份。步骤中的成品个数按两人份举例，换人数时调整个数，保持厚度。${portions>2?'请分批烹饪；':' '}时间按单锅参考，不随人数相乘。${r.prepMinutes?'含腌制/醒面约 '+r.prepMinutes+' 分钟。':''}</p><p class="note">锅具：${esc(r.equipment)}${r.pairing?`<br>搭配建议：${esc(r.pairing)}`:''}</p><h2>先把这些准备好</h2><div class="ingredients">${C.scale(r,portions).map(i=>`<div class="ingredient"><span>${i.name}</span><strong>${i.amount===0?'不另加':amt(i)}</strong></div>`).join('')}</div><p class="subtle">${r.allergens.length?'主要过敏原：'+r.allergens.join('、')+'。请另核对包装配料。':'请核对食材及包装配料，避免自身过敏原。'}</p><div class="detail-actions"><button class="primary" data-cook>开始做菜 →</button><button class="secondary" data-add="${r.id}">${basket.includes(r.id)?'✓ 已加入清单':'＋ 加入买菜清单'}</button></div><h2>照着做，一步一步来</h2>${r.steps.map(stepHtml).join('')}<h2>少走一点弯路</h2>${r.tips.map(t=>`<p class="note">${esc(t)}</p>`).join('')}${sourceHtml(r)}<p class="footer-note">${r.editorial}</p>`}<div id="timer-dock"></div></div>`;updateTimer();}
 function cookHtml(){const s=detail.steps[cookIndex];return `<div class="cook-progress"><div style="width:${(cookIndex+1)/detail.steps.length*100}%"></div></div><div class="eyebrow">${detail.name} · ${portions} 人份 · ${s.heat}</div><div class="cook-card"><h2>${s.title}</h2><p>${esc(C.stepText(s.text,portions,2,detail))}</p><div class="check-note">做对的标志：${esc(C.stepText(s.check,portions,2,detail))}</div>${s.seconds?`<button class="timer-btn" data-timer="${cookIndex}">◷ 开始 ${C.duration(s.seconds)}计时</button>`:''}<div class="mini-ingredients">本次全部用料：${ingredientText(detail)}</div><div class="cook-nav"><button class="secondary" data-prev ${cookIndex===0?'disabled':''}>上一步</button><button class="primary" data-next>${cookIndex===detail.steps.length-1?'完成这道菜 ✓':'做好了，下一步 →'}</button></div><p class="footer-note">请保持应用在前台；手机休眠或切到其他应用时，不能保证按时响铃。回到应用会按实际时间恢复倒计时。</p></div>`;}
 function closeDetail(){if(cooking){cooking=false;detailRender();return;}$('#recipe-dialog').close();detail=null;render();}
 function beep(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=880;g.gain.value=.12;o.start();g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.5);o.stop(audioContext.currentTime+.5);}catch{}}
 function updateTimer(){const dock=$('#timer-dock');if(!timer){if(dock)dock.innerHTML='';return;}const remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));if(!remaining&&!timer.notified){timer.notified=true;write('timer',timer);beep();toast('计时结束，请检查食材是否熟透');}if(dock){const name=R.find(r=>r.id===timer.recipe)?.name||'';dock.innerHTML=`<div class="timer-dock"><span>${esc(name)} · ${esc(timer.title)}<br><strong>${remaining?String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0'):'时间到，请检查熟透'}</strong></span><button class="text-btn" data-stop-timer>结束计时</button></div>`;}}
 function changePage(){const hash=location.hash.slice(1);page=['home','recipes','favorites','shopping'].includes(hash)?hash:'home';if($('#recipe-dialog').open)$('#recipe-dialog').close();detail=null;cooking=false;group='';cuisine='';render();window.scrollTo(0,0);}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-reset-filters')){group='';cuisine='';difficulty=0;max=0;noSpicy=false;noNoodles=false;exclude='';query='';persist();render();return;}
  if(b.hasAttribute('data-draw')){selected=C.choose(pool(),recent,Math.random,R);if(selected){recent=[...recent,selected.id].slice(-10);write('recent',recent);}if(page==='home'){$('#random-result').innerHTML=result();$('#random-result').scrollIntoView({behavior:'smooth',block:'nearest'});}return;}
  if(b.dataset.difficulty!==undefined){difficulty=Number(b.dataset.difficulty);persist();render();return;}
  if(b.dataset.category!==undefined){group='';cuisine='';if(page==='home')category=b.dataset.category;else listCategory=b.dataset.category;persist();render();return;}
  if(b.dataset.open){detail=R.find(r=>r.id===b.dataset.open);cooking=false;detailRender();$('#recipe-dialog').showModal();$('#recipe-dialog').scrollTop=0;return;}
  if(b.dataset.save){const id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];write('saved',saved);if(detail)detailRender();else render();toast(saved.includes(id)?'已收藏，下次还做这道':'已取消收藏');return;}
  if(b.dataset.portions){portions=Math.max(1,Math.min(6,portions+Number(b.dataset.portions)));bought={};write('bought',bought);persist();if(detail)detailRender();else render();return;}
  if(b.hasAttribute('data-close')){closeDetail();return;}
  if(b.dataset.add){if(!basket.includes(b.dataset.add)){basket.push(b.dataset.add);bought={};write('basket',basket);write('bought',bought);}toast('已加入买菜清单');detailRender();return;}
  if(b.dataset.remove){basket=basket.filter(id=>id!==b.dataset.remove);bought={};write('basket',basket);write('bought',bought);render();return;}
  if(b.hasAttribute('data-cook')){cooking=true;cookIndex=0;detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.hasAttribute('data-prev')){cookIndex=Math.max(0,cookIndex-1);detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.hasAttribute('data-next')){done[detail.id+'-'+cookIndex]=true;if(cookIndex===detail.steps.length-1){cooking=false;toast('做好了！趁热享用，也记下下次想调整的味道。');}else cookIndex++;detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.dataset.timer!==undefined){const s=detail.steps[Number(b.dataset.timer)];if(timer&&timer.end>Date.now()&&!confirm('已有一个计时正在进行。结束它并开始新计时？'))return;timer={recipe:detail.id,title:s.title,end:Date.now()+s.seconds*1000,notified:false};write('timer',timer);try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}updateTimer();toast('计时已开始，请保持应用在前台');return;}
  if(b.hasAttribute('data-stop-timer')){timer=null;write('timer',null);updateTimer();return;}
 });
 document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;updateList();}if(e.target.id==='exclude'){exclude=e.target.value;persist();updateList();}});
 document.addEventListener('change',e=>{if(e.target.id==='cuisine'){cuisine=e.target.value;updateList();}if(e.target.id==='food-group'){group=e.target.value;updateList();}if(e.target.id==='no-noodles'){noNoodles=e.target.checked;updateList();}if(e.target.id==='max'){max=Number(e.target.value);persist();updateList();}if(e.target.id==='no-spicy'){noSpicy=e.target.checked;persist();updateList();}if(e.target.dataset.bought){bought[e.target.dataset.bought]=e.target.checked;write('bought',bought);e.target.closest('label').classList.toggle('checked',e.target.checked);}if(e.target.dataset.done!==undefined){done[detail.id+'-'+e.target.dataset.done]=e.target.checked;e.target.closest('.step').classList.toggle('done',e.target.checked);}});
 $('#recipe-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
 $('#help').onclick=()=>$('#guide-dialog').showModal();$('#close-guide').onclick=()=>$('#guide-dialog').close();
 window.appBack=()=>{if($('#guide-dialog').open){$('#guide-dialog').close();return true;}if($('#recipe-dialog').open){closeDetail();return true;}if(page!=='home'){location.hash='home';return true;}return false;};
 window.addEventListener('hashchange',changePage);document.addEventListener('visibilitychange',updateTimer);setInterval(updateTimer,1000);changePage();updateTimer();
})();
