(() => {
 'use strict';
 const R=window.RECIPES,C=window.CookCore,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

 R.forEach(r=>{r.initials=window.RECIPE_INITIALS?.[r.id]||'';r.pinyin=window.RECIPE_PINYIN?.[r.id]||'';});
 const native=window.Kitchen;
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem('cook-'+k))??f;}catch{return f;}};
 const migration=C.migrateStorage(localStorage,R);
 const write=(k,v)=>{if(!migration.writable){storageError=migration.reason;toast(storageError);return false;}try{localStorage.setItem('cook-'+k,JSON.stringify(v));return true;}catch{storageError='本机存储不可用，本次操作仅在当前页面保留';toast(storageError);return false;}};
 const ids=x=>Array.isArray(x)?x.filter(id=>R.some(r=>r.id===id)):[];
 let saved=ids(read('saved',[])),basket=ids(read('basket',[])),bought=read('bought',{}),prefs=read('prefs',{});
 prefs=C.normalizePrefs(prefs,R);if(!bought||typeof bought!=='object')bought={};
 let portions=Math.max(1,Math.min(6,Number(prefs.portions)||2)),category=prefs.category,max=[15,20,30,45].includes(Number(prefs.max))?Number(prefs.max):0,noSpicy=!!prefs.noSpicy,exclude=typeof prefs.exclude==='string'?prefs.exclude:'',query=prefs.query,page='home',selected=null,selectedCriteria='',recent=ids(read('recent',[])),detail=null,cooking=false,cookIndex=0,done={},progress=C.normalizeProgress(read('progress',{}),R);
 for(const [id,p] of Object.entries(progress))for(const n of p.checked)done[id+'-'+n]=true;
 let group=prefs.group,cuisine=prefs.cuisine,difficulty=[1,2,3].includes(Number(prefs.difficulty))?Number(prefs.difficulty):0,noNoodles=prefs.noNoodles;
 const difficultyLabels={1:'轻松做',2:'日常做',3:'挑战做'};
 const cuisineOrder=[...new Set(['川菜','湘菜','鲁菜','粤菜','苏菜','浙菜','闽菜','徽菜','京菜','津菜','东北风味','西北风味','家常风味',...R.map(r=>r.cuisine).filter(Boolean)])];let listingLimit=36;
 let history=read('history',[]);if(!Array.isArray(history))history=[];history=history.filter(h=>h&&R.some(r=>r.id===h.id)&&Number.isFinite(h.at)).slice(-200);
 let notes=C.normalizeNotes(read('notes',{}),R),linkMode=read('linkMode','choose')==='default'?'default':'choose',advancedOpen=null,noteDrafts={};
 let theme=read('theme','auto'),locked=false,unlockAt=0,lastNext=0,landscape=false;
 let timer=read('timer',null),toastHandle,audioContext;
 let shoppingPendingOnly=true,changedIngredients=new Set(),tutorialOpen=new Set(),storageError='';
 let requests=C.normalizeRequests(read('requests',[])),requestDraft={name:'',note:''},dialogLayer=0;
 function showDialog(el){el.dataset.layer=String(++dialogLayer);el.showModal();}
 function topDialog(){return [...document.querySelectorAll('dialog[open]')].sort((a,b)=>Number(a.dataset.layer||0)-Number(b.dataset.layer||0)).at(-1);}
 if(timer&&(!R.some(r=>r.id===timer.recipe)||!Number.isFinite(timer.end)))timer=null;
 function persist(resetBatch=true){if(resetBatch)listingLimit=36;write('prefs',{portions,category,max,noSpicy,exclude,difficulty,noNoodles,group,cuisine,query});}
 function toast(message){const dialog=document.activeElement?.closest('dialog[open]')||topDialog();let el=$('#toast');if(dialog){el=dialog.querySelector('.local-toast');if(!el){el=document.createElement('div');el.className='local-toast';el.setAttribute('role','status');dialog.append(el);}}document.querySelectorAll('#toast.visible,.local-toast.visible').forEach(other=>{if(other!==el)other.classList.remove('visible');});el.textContent=message;el.classList.add('visible');clearTimeout(toastHandle);toastHandle=setTimeout(()=>el.classList.remove('visible'),4500);}
 const amt=i=>C.amount(i);
 const total=R.length,breakfastCount=R.filter(r=>r.category==='早餐').length,homeCount=total-breakfastCount;
 const ingredientText=r=>C.scale(r,portions).filter(i=>i.amount>0).map(i=>i.name+' '+amt(i)).join(' · ');
 const tones=['#ece9d9','#eee2d3','#e6ebdc','#f1e7d7','#e6e8e0'];
 function foodImage(r,extra=''){const [x,y,w,h]=r.image.rect,[sw,sh]=r.image.size;return `<div class="food-image ${extra}" role="img" aria-label="${esc(r.name+'成品参考')}" style="--food-image:url('${r.image.sheet}');--food-size:${sw/w*100}% ${sh/h*100}%;--food-x:${x/(sw-w)*100}%;--food-y:${y/(sh-h)*100}%;--food-ratio:${w}/${h}"></div>`;}

 function filterState(){return {category,max,noSpicy,exclude,query,group,cuisine,difficulty,noNoodles};}
 function criteria(){return JSON.stringify(filterState());}
 function saveProgress(){if(!detail)return;progress[detail.id]={index:cookIndex,checked:detail.steps.map((_,i)=>i).filter(i=>done[detail.id+'-'+i]),updatedAt:Date.now(),revision:detail.revision};write('progress',progress);}
 function clearProgress(id){delete progress[id];for(const k of Object.keys(done))if(k.startsWith(id+'-'))delete done[k];write('progress',progress);}
 function recommendations(){return C.suggestions(R,filterState(),new Date().toLocaleDateString('en-CA')).map(card).join('');}
 function selectionControls(){const count=pool().length;return `<p class="match-count" aria-live="polite">当前符合 <strong>${count}</strong> 道</p><button class="primary draw-button" data-draw ${count?'':'disabled'}>✦ ${selected?'按当前条件再抽一道':'按这些条件抽一道'}</button>`;}
 const minutesLabel=n=>n<60?n+' 分钟':Math.floor(n/60)+' 小时'+(n%60?' '+n%60+' 分钟':'');
 function card(r,n=0){return `<article class="recipe-card"><button class="card-open" data-open="${r.id}" aria-label="查看${r.name}菜谱"><div class="card-visual" style="--tone:${tones[n%tones.length]}"><span class="badge">${r.group||r.category}</span>${foodImage(r)}</div><div class="card-body"><h3>${r.name}</h3>${history.some(h=>h.id===r.id&&new Date(h.at).toDateString()===new Date().toDateString())?'<span class="cooked-tag">今天做过</span>':''}<p>${difficultyLabels[r.difficulty]} · ${minutesLabel(r.minutes)} · ${r.ingredients.filter(i=>i.amount>0).slice(0,2).map(i=>i.name).join(' / ')}</p></div></button><button class="save-btn ${saved.includes(r.id)?'saved':''}" data-save="${r.id}" aria-label="${saved.includes(r.id)?'取消收藏':'收藏'}${r.name}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'♥':'♡'}</button></article>`;}
 function serving(){return `<div class="serving"><span>用餐人数</span><button data-portions="-1" aria-label="减少人数" ${portions===1?'disabled':''}>−</button><strong>${portions} 人</strong><button data-portions="1" aria-label="增加人数" ${portions===6?'disabled':''}>+</button></div>`;}
 function filters(){return `<div class="segmented" aria-label="菜谱类别">${['','家常菜','早餐'].map(c=>`<button data-category="${c}" class="${category===c?'active':''}" aria-pressed="${category===c}">${c||'全部'}${c==='家常菜'?' · '+homeCount:c==='早餐'?' · '+breakfastCount:''}</button>`).join('')}</div>`;}
 function modes(){return `<div class="difficulty-picker" aria-label="按做菜难度筛选">${[[0,'全部难度','随心选择'],[1,'轻松做','基础操作'],[2,'日常做','练练火候'],[3,'挑战做','多些技巧']].map(([n,t,sub])=>`<button data-difficulty="${n}" class="${difficulty===n?'active':''}" aria-pressed="${difficulty===n}"><strong>${t}</strong><small>${sub}</small></button>`).join('')}</div><p class="difficulty-hint">难度看操作，用时单独选。慢炖也可以很简单。</p>`;}
 function variety(){const cat=category;const groups=[...new Set(R.filter(r=>!cat||r.category===cat).map(r=>r.group))];return `${modes()}<div class="variety-controls">${cat!=='早餐'?`<label>想吃哪地 <select id="cuisine" aria-label="菜系"><option value="">全部菜系</option>${cuisineOrder.filter(c=>R.some(r=>r.cuisine===c)).map(c=>`<option value="${c}" ${cuisine===c?'selected':''}>${c}${c==='鲁菜'?'（山东）':''}</option>`).join('')}</select></label>`:''}<label>想吃哪种 <select id="food-group" aria-label="菜品种类"><option value="">各种都试试</option>${groups.map(g=>`<option value="${esc(g)}" ${group===g?'selected':''}>${g}</option>`).join('')}</select></label><label><input id="no-noodles" type="checkbox" ${noNoodles?'checked':''}>这次不吃面条粉类</label><button class="text-btn" data-reset-filters>重置筛选 · 保留忌口</button></div>`;}
 function options(){return `<div class="controls"><label>预计用时 <select id="max" aria-label="最长用时">${[[0,'不限'],[15,'15分钟内'],[20,'20分钟内'],[30,'30分钟内'],[45,'45分钟内']].map(([v,t])=>`<option value="${v}" ${max===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="toggle"><input id="no-spicy" type="checkbox" ${noSpicy?'checked':''}>不吃辣</label></div>`;}
 function advancedFilters(){const labels=[cuisine,group,difficulty?difficultyLabels[difficulty]:'',noNoodles?'不吃面条':'',exclude?'排除 '+exclude:''].filter(Boolean);return `<details class="advanced-filters" ${(advancedOpen===null?labels.length>0:advancedOpen)?'open':''}><summary>更多条件 <span>${esc(labels.join(' · ')||'菜系、难度、忌口')}</span></summary><input id="exclude" class="exclude" aria-label="排除食材" placeholder="不想吃的食材，如：香菜、牛肉" value="${esc(exclude)}">${variety()}</details>`;}
 const pool=()=>C.filter(R,{category,max,noSpicy,exclude,query,group,cuisine,difficulty,noNoodles});
 function empty(title,text){return `<div class="empty"><div class="big">🥣</div><h3>${title}</h3><p>${text}</p></div>`;}
 function noResults(){
   const f={category,noSpicy,exclude,query,group,cuisine,difficulty,noNoodles};
   const candidates=C.filter(page==='favorites'?R.filter(r=>saved.includes(r.id)):R,f);
   const next=max?candidates.filter(r=>r.minutes>max).sort((a,b)=>a.minutes-b.minutes)[0]:null;
   return relatedHtml()+empty('这些条件暂时没有匹配',`${max?'当前限制 '+max+' 分钟，包含切配和腌制时间。':''}${next?'保留菜系、难度和忌口后，最快需要 '+next.minutes+' 分钟。':'可试着换菜系、难度或搜索词。'}`)+`<div class="empty-actions">${next?`<button class="secondary" data-relax-time>取消用时限制 · 保留忌口</button>`:''}<button class="secondary" data-browse>查看菜谱</button><button class="secondary" data-clear-discovery>清除菜系与搜索 · 保留忌口</button><button class="text-btn" data-request-open>想吃的菜还没有？告诉我们</button></div>`;
 }
 function relatedHtml(){const catalog=page==='favorites'?R.filter(r=>saved.includes(r.id)):R,near=C.nearbyNames(C.filter(catalog,{...filterState(),query:''}),query);return near.length?`<section class="search-suggestions" aria-label="近似菜名"><h3>你可能想找</h3><p>菜名可能不同，点开看看做法。仍按当前条件推荐。</p><div>${near.map(r=>`<button class="secondary" data-open="${r.id}">${esc(r.name)}</button>`).join('')}</div></section>`:'';}
 function preserveBought(before){const after=C.shopping(R,basket,portions),keep=C.reconcileBought(before,after,bought),old=new Map(before.map(i=>[i.key,i.amount]));changedIngredients=new Set(after.filter(i=>old.has(i.key)&&i.amount>old.get(i.key)).map(i=>i.key));const changed=Object.keys(bought).filter(k=>bought[k]&&!keep[k]).length;bought=keep;write('bought',bought);if(changed)toast('用量增加的食材需重新核对，其余已购买状态保留');}
 function nativeStatus(){try{return native?JSON.parse(native.timerStatus()):{};}catch{return {};}}
 function timerHelp(){const st=nativeStatus();return native?`${st.exact&&st.notifications?'系统计时提醒已就绪':'后台提醒未就绪，请在设置中开启通知和精确计时'}。声音仍受系统音量、勿扰和省电设置影响；强行停止或重启手机后需重新计时。`:'网页计时仅在前台提醒；安装安卓应用可开启系统提醒。';}
 function applyTheme(){if(!['auto','light','dark'].includes(theme))theme='auto';document.documentElement.dataset.theme=theme==='auto'?((native?native.systemDark():window.matchMedia?.('(prefers-color-scheme: dark)').matches)?'dark':'light'):theme;if(native)native.appearance(document.documentElement.dataset.theme==='dark');}
 function settingsRender(){const st=nativeStatus();$('#settings-content').innerHTML=`<h2>我的厨房</h2><label class="setting-label">外观 <select id="theme"><option value="auto" ${theme==='auto'?'selected':''}>跟随系统</option><option value="light" ${theme==='light'?'selected':''}>明亮</option><option value="dark" ${theme==='dark'?'selected':''}>深色</option></select></label><h3>教程打开方式</h3><label class="setting-label">打开链接 <select id="link-mode"><option value="choose" ${linkMode==='choose'?'selected':''}>每次选择打开方式</option><option value="default" ${linkMode==='default'?'selected':''}>使用手机默认方式</option></select></label><p class="note">可选择浏览器或能打开链接的平台应用。</p><h3>计时提醒</h3><p class="note">${timerHelp()}</p>${native?`<div class="settings-actions"><button class="secondary" data-notifications>通知与声音：${st.notifications?'已开启':'未开启'}</button><button class="secondary" data-exact>精确计时：${st.exact?'已开启':'未开启'}</button></div><p class="note">开启后请重新开始步骤计时。也可在步骤旁交给系统时钟；系统时钟中的计时需要在时钟里结束。</p>`:''}<details class="image-info"><summary>菜谱图片说明</summary><p class="note">图片为 AI 生成的成品参考，外观会随食材和做法变化。判断熟透请看步骤中的检查点。</p></details><h3>想吃的菜还没有？</h3><p class="note">记下想吃的菜，也可以提交给我们。</p><button class="secondary" data-request-open>我的补菜建议 · ${requests.length}</button><h3>备份与恢复</h3><p class="note">将收藏、买菜清单、已购买状态、口味偏好、外观、步骤进度、做菜笔记、补菜建议及记录保存为文件。卸载前先导出。备份不包含正在运行的计时；文件中包含你的偏好，请自行保管。</p><div class="settings-actions"><button class="primary" data-export>导出备份</button><button class="secondary" data-import>导入备份</button></div><h3>最近做过 <small>最多保留200次</small></h3>${history.length?`<div class="history-list">${history.slice(-30).reverse().map(h=>`<button class="history-item" data-history-open="${h.id}"><span>${esc(R.find(r=>r.id===h.id).name)}</span><small>${new Date(h.at).toLocaleDateString('zh-CN')}</small></button>`).join('')}</div><button class="text-btn" data-clear-history>清空做菜记录</button>`:'<p class="note">完成做菜模式，或在菜谱里点“今天做过”，即可记录。最近7天做过的菜会在随机推荐中尽量避开；没有其他候选时仍可能推荐。</p>'}`;}
 function todayCooked(id){return history.some(h=>h.id===id&&new Date(h.at).toDateString()===new Date().toDateString());}
 function recordCooked(id){if(todayCooked(id))return false;history=[...history,{id,at:Date.now()}].slice(-200);return write('history',history);}
 function resetDiscovery(){category='';group='';cuisine='';difficulty=0;max=0;noNoodles=false;query='';persist();}
 function finishRecipe(){const id=detail.id;recordCooked(id);clearProgress(id);if(timer?.recipe===id){native?.cancelTimer();timer=null;write('timer',null);}cooking=false;landscape=false;detailRender();$('#recipe-dialog').scrollTop=0;toast('做好了，趁热享用！');}
 function exportData(){return JSON.stringify({app:'cookdaily',schema:4,exportedAt:new Date().toISOString(),data:{saved,basket,bought,prefs:{portions,category,max,noSpicy,exclude,difficulty,noNoodles,group,cuisine,query},recent,history,theme,progress,notes,linkMode,requests}},null,2);}
 function requestsRender(){const focus=captureFocus($('#requests-dialog')),box=$('#requests-content');box.innerHTML=`<p class="note">先保存在手机里，离线也能记录。提交需联网并登录 GitHub，内容会公开，请勿填写个人信息。</p><label class="request-field">想吃什么菜<input id="request-name" maxlength="40" value="${esc(requestDraft.name)}" placeholder="如：葱爆羊肉" autocomplete="off"></label><label class="request-field">口味或做法 <small>可不填</small><textarea id="request-note" maxlength="300" placeholder="如：不辣、汤汁多一些…">${esc(requestDraft.note)}</textarea></label><button class="primary" data-request-save>保存到我的补菜建议</button><p class="request-help">已有同名建议时会更新备注。保存后可提交给我们。</p><h3>我的建议 <small>${requests.length} / 200</small></h3>${requests.length?requests.map((r,i)=>({r,i})).reverse().map(({r,i})=>`<article class="request-item"><h4>${esc(r.name)}</h4>${r.note?`<p>${esc(r.note)}</p>`:''}<small>保存在本机</small><div><a class="primary" data-external data-request-submit="${i}" target="_blank" rel="noopener noreferrer" href="${esc(C.recipeRequestUrl(r))}">提交给我们 ↗</a><button class="secondary" data-request-copy="${i}">复制建议</button><button class="text-btn" data-request-remove="${i}" aria-label="删除${esc(r.name)}的本机建议">删除</button></div></article>`).join(''):'<p class="note">把想吃的菜名记在这里吧。</p>'}`;restoreFocus($('#requests-dialog'),focus);}
 function saveRequest(){const name=$('#request-name').value.trim(),note=$('#request-note').value.trim();if(!name||name.length>40||note.length>300){toast('请填写菜名（最多40字），备注最多300字');$('#request-name').focus();return;}const item={name,note,at:Date.now()},key=C.normalize(name).replace(/\s/g,''),index=requests.findIndex(r=>C.normalize(r.name).replace(/\s/g,'')===key);if(index<0&&requests.length>=200){toast('最多保存200条建议，请先删除已解决的建议');return;}const next=index<0?[...requests,item]:requests.map((r,i)=>i===index?item:r);if(!write('requests',next))return;requests=next;requestDraft={name:'',note:''};requestsRender();toast(index<0?'已保存在手机里；可继续提交给我们':'同名建议已更新；可继续提交给我们');}
 window.nativeMessage=toast;
 window.receiveBackup=text=>{try{if(!migration.writable)throw new Error(migration.reason);if(text.length>1000000)throw new Error('文件过大');const data=C.validateBackup(JSON.parse(text),R);if(!confirm(`将恢复 ${data.saved.length} 道收藏、${data.basket.length} 道买菜清单和 ${data.history.length} 次做菜记录，替换对应本机记录。${'requests' in data?'补菜建议也会被恢复。':'旧备份不含补菜建议，现有建议会保留。'}建议先导出当前备份。是否继续？`))return;
   const keys=Object.keys(data),old=keys.map(k=>[k,localStorage.getItem('cook-'+k)]);
   try{for(const k of keys)localStorage.setItem('cook-'+k,JSON.stringify(data[k]));}catch(e){for(const [k,v] of old){if(v===null)localStorage.removeItem('cook-'+k);else localStorage.setItem('cook-'+k,v);}throw new Error('存储空间不足，未导入');}
   ({saved,basket,bought,recent,history,theme,progress,notes,linkMode}=data);if('requests' in data)requests=data.requests;({portions,category,max,noSpicy,exclude,difficulty,noNoodles,group,cuisine,query}=data.prefs);done={};noteDrafts={};for(const [id,p] of Object.entries(progress))for(const n of p.checked)done[id+'-'+n]=true;selected=null;selectedCriteria='';applyTheme();render();settingsRender();toast('备份恢复完成；当前计时未改变');
 }catch(e){toast('未导入：'+(e instanceof SyntaxError?'不是有效的 JSON 备份':e.message));}};
 async function copyShopping(text,label='买菜清单'){if(native?.copyText){if(native.copyText(text))toast(label+'已复制');else showShoppingText(text,label);return;}try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);toast(label+'已复制');return;}}catch{}const box=document.createElement('textarea');box.value=text;box.setAttribute('aria-label','待复制'+label);box.style.position='fixed';box.style.opacity='0';document.body.append(box);const focus=document.activeElement;box.select();let copied=false;try{copied=document.execCommand('copy');}catch{}box.remove();focus?.focus({preventScroll:true});if(copied)toast(label+'已复制');else showShoppingText(text,label);}
 function showShoppingText(text,label='买菜清单'){$('#shopping-export-dialog .dialog-header strong').textContent=label;$('#shopping-export-dialog').setAttribute('aria-label',label+'文本');$('#shopping-export-text').setAttribute('aria-label',label+'文本');$('#shopping-export-text').value=text;showDialog($('#shopping-export-dialog'));toast('可长按文字复制');}
 async function takeShopping(share){const text=C.shoppingText(R,basket,portions,bought,shoppingPendingOnly);if(!text){toast('食材都已买齐；取消“只复制 / 分享待买食材”可带走完整清单');return;}if(share){if(native?.shareText){if(!native.shareText(text))showShoppingText(text);return;}if(navigator.share){try{await navigator.share({title:'买菜清单',text});return;}catch(e){if(e.name==='AbortError')return;}}showShoppingText(text);return;}await copyShopping(text);}
 function showTimerHint(){const st=nativeStatus();if(!native||timer?.mode==='native'||(st.exact&&st.notifications)||read('timerHelpSeen',false))return;write('timerHelpSeen',true);$('#timer-hint-text').textContent='这次计时已开始，但'+(!st.notifications&&!st.exact?'通知和精确计时尚未开启':!st.notifications?'通知尚未开启':'精确计时尚未开启')+'，切到其他应用或锁屏后可能无法提醒。开启后请重新开始计时，也可交给系统时钟。';showDialog($('#timer-permission-dialog'));}
 function exportBackup(){const content=exportData();if(native){native.exportBackup(content);return;}const url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='今天吃什么-备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 function home(){return `<section class="home-intro"><div class="eyebrow">好好吃饭，从这一餐开始</div><h1>今天想吃什么？</h1><span class="pill">${total} 道菜谱 · 离线可看</span></section><section class="home-entries" aria-label="找菜入口"><button class="browse-entry" data-browse><span class="entry-icon" aria-hidden="true">▤</span><span><strong>查看菜谱</strong><small>按菜系、食材挑选 · ${total} 道菜</small></span><span class="entry-arrow" aria-hidden="true">→</span></button><button class="request-entry" data-request-open><span>想吃的菜还没有？</span><strong>告诉我们 ＋</strong></button></section><section class="random-box"><div class="section-head"><h2>① 选好条件</h2></div>${filters()}<input class="search" id="search" value="${esc(query)}" placeholder="菜名或食材，可留空" aria-label="搜索菜名或食材">${options()}${advancedFilters()}<div id="home-related">${pool().length?relatedHtml():''}</div><h2 class="draw-heading">② 抽一道菜</h2><div id="selection-controls">${selectionControls()}</div><div id="random-result">${result()}</div></section><div class="section-head"><h2>也可以直接选</h2><button class="text-btn" data-browse>更多菜谱 →</button></div><div id="home-suggestions" class="recipe-grid">${recommendations()}</div>`;}
 function result(){const count=pool().length;if(!selected)return count?`<div class="awaiting-draw">条件选好了，就点上方按钮。<br>这里会显示你抽中的菜。</div>`:noResults();const stale=selectedCriteria!==criteria();if(!count)return noResults()+`<div class="previous-result"><span>上次抽到：${esc(selected.name)}</span><button class="text-btn" data-open="${selected.id}">查看这道菜</button></div>`;const canChange=count>1||!pool().some(r=>r.id===selected.id);return `<div class="random-result" aria-live="polite">${foodImage(selected,'result-picture')}<div><span class="eyebrow">${stale?'上次抽选 · 条件已改变':'本次抽中的菜'}</span><h3 id="drawn-title" tabindex="-1">${esc(selected.name)}</h3><div class="meta"><span>◷ ${minutesLabel(selected.minutes)}</span>${selected.cuisine?`<span>${esc(selected.cuisine)}</span>`:''}<span>${difficultyLabels[selected.difficulty]}</span><span>${selected.group}</span></div>${stale?'<p class="stale-note">按新条件再抽，结果由你决定。</p>':''}</div><div class="result-actions"><button class="primary" data-open="${selected.id}">看做法 →</button><button class="secondary" data-draw data-redraw ${canChange?'':'disabled'}>${stale?'按新条件抽一道':canChange?'换一道':'只有这一道'}</button></div></div>`;}
 function cuisineBrowse(){if(category==='早餐'||page==='favorites')return '';const choices=cuisineOrder.filter(c=>R.some(r=>r.cuisine===c));return `<section class="cuisine-browse" aria-label="按菜系找菜"><div class="cuisine-label"><strong>按菜系找菜</strong><span>左右滑动</span></div><div class="cuisine-chips"><button data-cuisine="" aria-pressed="${!cuisine}">全部菜系</button>${choices.map(c=>`<button data-cuisine="${esc(c)}" aria-pressed="${cuisine===c}">${esc(c)} <small>${R.filter(r=>r.cuisine===c).length}</small></button>`).join('')}</div></section>`;}
 function listingResults(){const list=C.rankResults(page==='favorites'?pool().filter(r=>saved.includes(r.id)):pool(),query);const count=page==='favorites'?`共收藏 ${saved.length} 道 · 当前符合 ${list.length} 道`:`共 ${list.length} 道`;const content=list.length?`<div class="recipe-grid">${list.slice(0,listingLimit).map(card).join('')}</div>${list.length>listingLimit?`<div class="load-more"><p>已显示 ${listingLimit} / ${list.length} 道</p><button class="secondary" data-more>再看 ${Math.min(36,list.length-listingLimit)} 道 ↓</button></div>`:''}`:page==='favorites'?(saved.length?relatedHtml()+empty('收藏都在，只是被条件筛掉了','试着调整条件，或查看全部收藏。')+`<div class="empty-actions"><button class="secondary" data-show-all-saved>查看全部收藏 · 保留忌口</button></div>`:empty('还没有收藏','在喜欢的菜谱上点一下爱心，随时回来找。')+`<div class="empty-actions"><a class="primary" href="#recipes">去找喜欢的菜</a></div>`):noResults();return `<p class="count" aria-live="polite">${count}</p>${content}${list.length?relatedHtml():''}${list.length||page==='favorites'?'<div class="list-request"><button class="secondary" data-request-open>想吃的菜还没有？告诉我们 ＋</button></div>':''}`;}
 function listing(){return `<div class="eyebrow">${page==='favorites'?'收藏喜欢的味道':'每天一道好菜'}</div><h1 class="page-title">${page==='favorites'?'我的收藏':'全部菜谱'}</h1><p class="subtle">${page==='favorites'?'喜欢的味道，留给下一顿。':`${homeCount} 道家常菜 · ${breakfastCount} 道早餐`}</p><input class="search" id="search" value="${esc(query)}" placeholder="菜名 / 食材 / 拼音，如 hongshaorou" aria-label="搜索菜名或食材"><div class="filters">${filters()}${cuisineBrowse()}${options()}${advancedFilters()}</div><div id="list-results">${listingResults()}</div>`;}
 function shopping(){const list=C.shoppingItems(R,basket,portions),pending=list.filter(i=>!bought[i.key]).length;return `<div class="eyebrow">先买齐，再开火</div><h1 class="page-title">买齐这一餐</h1><p class="subtle">同名同单位的食材已合并；清水不列入采购。</p>${serving()}<section>${basket.map(id=>{const r=R.find(x=>x.id===id);return `<div class="shop-recipe"><span>${r.emoji}</span><button class="text-btn name" data-open="${r.id}">${esc(r.name)}</button><button class="text-btn" data-remove="${id}" aria-label="从清单移除${r.name}">移除</button></div>`;}).join('')}</section>${list.length?`<section class="shopping-tools" aria-label="带走买菜清单"><p id="shopping-count" role="status">待买 ${pending} 项 · 已买 ${list.length-pending} 项</p><label><input id="shopping-pending" type="checkbox" ${shoppingPendingOnly?'checked':''}>只复制 / 分享待买食材</label><div><button class="secondary" data-copy-shopping>复制清单</button><button class="secondary" data-share-shopping>分享清单</button></div></section>`:''}<div class="shopping-items">${list.length?list.map(i=>`<label class="shop-item ${bought[i.key]?'checked':''} ${changedIngredients.has(i.key)?'amount-changed':''}"><input type="checkbox" data-bought="${esc(i.key)}" ${bought[i.key]?'checked':''}><span>${esc(i.name)}${changedIngredients.has(i.key)?'<small>用量增加，请核对</small>':''}</span><strong>${amt(i)}</strong></label>`).join(''):empty('清单还是空的','在菜谱里点击“加入买菜清单”，一餐所需一目了然。')}</div>`;}
 function captureFocus(root){const el=document.activeElement;if(!root?.contains(el))return null;if(el.id)return {id:el.id};const a=[...el.attributes].find(a=>a.name.startsWith('data-'));return a?{attr:a.name,value:a.value}:null;}
 function restoreFocus(root,mark){if(!mark)return;const el=mark.id?[...root.querySelectorAll('[id]')].find(e=>e.id===mark.id):[...root.querySelectorAll('['+mark.attr+']')].find(e=>e.getAttribute(mark.attr)===mark.value);if(el&&!el.disabled)el.focus({preventScroll:true});}
 function render(){const focus=captureFocus($('#main'));document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));$('#main').innerHTML=page==='home'?home():page==='shopping'?shopping():listing();restoreFocus($('#main'),focus);}
 function updateList(){listingLimit=36;const summary=$('.advanced-filters>summary span');if(summary)summary.textContent=[cuisine,group,difficulty?difficultyLabels[difficulty]:'',noNoodles?'不吃面条':'',exclude?'排除 '+exclude:''].filter(Boolean).join(' · ')||'菜系、难度、忌口';document.querySelectorAll('[data-cuisine]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cuisine===cuisine)));if(page==='home'){$('#selection-controls').innerHTML=selectionControls();$('#random-result').innerHTML=result();$('#home-suggestions').innerHTML=recommendations();$('#home-related').innerHTML=pool().length?relatedHtml():'';}else if(page==='recipes'||page==='favorites')$('#list-results').innerHTML=listingResults();}
 function tutorialHtml(r){return `<details class="tutorial-panel" aria-label="视频教程" data-tutorial="${r.id}" ${tutorialOpen.has(r.id)?'open':''}><summary><strong>▷ 看视频做法</strong><span>联网打开</span></summary><div class="tutorial-links"><a data-external href="https://search.bilibili.com/all?keyword=${encodeURIComponent(r.name+' 家常做法')}">▷ B站搜教程 ↗</a><a data-external href="https://www.douyin.com/search/${encodeURIComponent(r.name+' 做法')}">▷ 抖音搜教程 ↗</a>${r.videos.map(v=>`<a data-external href="${esc(v.url)}">▷ 相关视频 ↗</a>`).join('')}</div><p>搜索结果做法可能不同；平台可能需要登录。</p></details>`;}
 function sourceHtml(r){return `<details class="source-disclosure"><summary>参考资料与更多图片</summary><div class="sources">${r.sources.map(a=>`<a data-external href="${esc(a.url)}">${esc(a.title)} ↗</a>`).join('')}<a data-external href="https://www.bing.com/images/search?q=${encodeURIComponent(r.name+' 家常菜 成品')}">搜索成品图片 ↗</a></div></details>`;}
 function journalHtml(r){return `<section class="recipe-journal"><h2>我的做菜笔记</h2><label class="sr-only" for="recipe-note">这道菜的个人笔记</label><textarea id="recipe-note" maxlength="1000" placeholder="下次少放一点盐，或记下家人喜欢的口味…">${esc(noteDrafts[r.id]??notes[r.id]?.text??'')}</textarea><div><button class="secondary" data-journal-save>保存笔记</button><span>只保存在本机，可随备份导出。</span></div></section>`;}
 function recipeBody(r){const allDone=r.steps.every((_,i)=>done[r.id+'-'+i]);return `<div class="recipe-overview"><div class="overview-copy"><h1>${esc(r.name)}</h1><div class="meta"><span>◷ 约 ${minutesLabel(r.minutes)}</span><span>${r.spicy?'有辣':'不辣'}</span>${r.cuisine?`<span>${esc(r.cuisine)}</span>`:''}<span>${difficultyLabels[r.difficulty]}</span></div><small>${esc(r.difficultyReason)}</small></div><figure class="dish-figure">${foodImage(r,'detail-picture')}</figure></div>${serving()}<div class="detail-actions"><button class="primary" ${allDone?'data-finish-recipe':'data-cook'}>${allDone?'完成并记录 ✓':progress[r.id]?'继续做到第'+(progress[r.id].index+1)+'步 →':'开始做菜 →'}</button><button class="secondary" data-add="${r.id}">${basket.includes(r.id)?'✓ 已加入清单':'＋ 买菜清单'}</button>${progress[r.id]?'<button class="text-btn" data-restart>重新开始</button>':''}</div>${tutorialHtml(r)}<details class="prep-details"><summary>用时、锅具与搭配</summary><p>${r.timing?`两人份：备料${r.timing.prep}分钟 + 加热${r.timing.cook}分钟 + 收尾${r.timing.finish}分钟。`:''}初次做或增加人数，用时可能更久。${r.prepMinutes?'含准备/等待约'+minutesLabel(r.prepMinutes)+'。':''}</p><p>锅具：${esc(r.equipment)}${r.pairing?`<br>搭配：${esc(r.pairing)}`:''}</p></details><h2 id="ingredient-heading">准备食材 <small>${portions} 人份</small></h2><p class="portion-note">${portions>2?'多人份请分批做，保持原来的切块大小、饼厚和碗深。':'人数改变时食材自动换算；单锅烹饪时间以食材状态为准。'}</p><div class="ingredients">${C.scale(r,portions).filter(i=>i.amount>0).map(i=>`<div class="ingredient"><span>${esc(i.name)}</span><strong>${amt(i)}</strong></div>`).join('')}</div><section class="allergen-alert" aria-label="过敏原提示"><strong>过敏原</strong><div class="allergen-tags">${r.allergens.map(a=>`<span>${esc(a)}</span>`).join('')}</div>请核对酱料与半成品包装配料。</section><h2>照着做，一步一步来</h2>${r.steps.map(stepHtml).join('')}<h2>做好这道菜的小窍门</h2>${r.tips.map(t=>`<p class="note">${esc(t)}</p>`).join('')}<button class="secondary" data-record="${r.id}" ${todayCooked(r.id)?'disabled':''}>${todayCooked(r.id)?'✓ 今天已做过':'✓ 今天做过这道菜'}</button>${journalHtml(r)}${sourceHtml(r)}`;}
 function stepHtml(s,i){return `<section class="step ${done[detail.id+'-'+i]?'done':''}"><div class="step-top"><span class="step-num">${String(i+1).padStart(2,'0')}</span><h3>${s.title}</h3><small>${s.heat}</small></div><p>${esc(C.stepText(s.text,portions,2,detail))}</p><div class="check-note">做对的标志：${esc(C.stepText(s.check,portions,2,detail))}</div>${s.seconds?`<button class="timer-btn" data-timer="${i}">◷ 计时 ${C.duration(s.seconds)}</button>`:''}<label class="step-check"><input type="checkbox" data-done="${i}" ${done[detail.id+'-'+i]?'checked':''}>这一步做好了</label></section>`;}
 function detailRender(){if(!detail)return;const r=detail,dlg=$('#recipe-dialog'),focus=captureFocus(dlg);dlg.classList.toggle('cooking-mode',cooking);if(native)native.cooking(cooking);dlg.innerHTML=`<div class="dialog-header"><button class="icon-btn" data-close aria-label="${cooking?'返回菜谱':'关闭菜谱'}">${cooking?'‹':'×'}</button><strong>${cooking?'跟着做 · '+(cookIndex+1)+' / '+r.steps.length:'把这道菜做好'}</strong><button class="icon-btn" data-save="${r.id}" aria-label="${saved.includes(r.id)?'取消收藏':'收藏'}${r.name}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'♥':'♡'}</button></div><div class="detail">${cooking?cookHtml():recipeBody(r)}<div id="timer-dock"></div></div>${locked&&cooking?'<div class="touch-lock"><strong>触控已锁定</strong><p>防止油手、擦屏误触</p><button class="primary" data-unlock>连续点两次解锁</button></div>':''}`;updateTimer();restoreFocus(dlg,focus);}
 function cookHtml(){const s=detail.steps[cookIndex];return `<div class="cook-tools"><button class="secondary" data-lock>锁住触控</button>${native?`<button class="secondary" data-landscape>${landscape?'跟随方向':'横屏做菜'}</button>`:''}</div><div class="cook-progress"><div style="width:${(cookIndex+1)/detail.steps.length*100}%"></div></div><div class="eyebrow">${detail.name} · ${portions} 人份 · ${s.heat}</div><div class="cook-card"><h2>${s.title}</h2><p>${esc(C.stepText(s.text,portions,2,detail))}</p><div class="check-note">做对的标志：${esc(C.stepText(s.check,portions,2,detail))}</div>${s.seconds?`<button class="timer-btn" data-timer="${cookIndex}">◷ 开始 ${C.duration(s.seconds)}计时</button>`:''}${s.seconds&&native?`<button class="timer-btn" data-system-timer="${cookIndex}">交给系统时钟 ↗</button>`:''}<div class="mini-ingredients">本次全部用料：${ingredientText(detail)}</div><div class="cook-nav"><button class="secondary" data-prev ${cookIndex===0?'disabled':''}>上一步</button><button class="primary" data-next>${cookIndex===detail.steps.length-1?'完成这道菜 ✓':'做好了，下一步 →'}</button></div><p class="footer-note">${timerHelp()}</p></div>`;}
 function closeDetail(){if(locked){toast('请先连续点两次解锁');return;}if(cooking){cooking=false;landscape=false;detailRender();return;}const id=detail?.id;$('#recipe-dialog').close();detail=null;render();updateTimer();$('#main [data-open=\"'+id+'\"]')?.focus({preventScroll:true});}
 function beep(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=880;g.gain.value=.12;o.start();g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.5);o.stop(audioContext.currentTime+.5);}catch{}}
 function updateTimer(){const dock=$('#timer-dock'),global=$('#global-timer');if(!timer){if(dock)dock.innerHTML='';global.innerHTML='';return;}
   const st=nativeStatus();let remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));
   if(timer.mode==='native'&&(!st.exact||!st.notifications)){native?.cancelTimer();timer.mode='foreground';write('timer',timer);}if(timer.mode==='native'&&st.token===timer.token){if(st.active)remaining=Math.ceil(st.remaining/1000);else if(st.fired)remaining=0;else {timer.mode='foreground';write('timer',timer);}}
   if(!remaining&&!timer.notified){timer.notified=true;write('timer',timer);if(timer.mode!=='native'||!st.exact||!st.notifications)beep();toast('计时结束，请检查食材是否熟透');}
   const name=R.find(r=>r.id===timer.recipe)?.name||'';
   const clock=remaining?(remaining>=3600?String(Math.floor(remaining/3600)).padStart(2,'0')+':':'')+String(remaining>=3600?Math.floor(remaining%3600/60):Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0'):'时间到，请检查熟透';
   const status=timer.mode==='native'&&st.exact&&st.notifications?'系统提醒已安排':'仅前台提醒；锁屏前请检查设置';
   const html=`<div class="timer-dock"><span>${esc(name)} · ${esc(timer.title)}<br><strong>${clock}</strong><small>${status}</small></span><button class="text-btn" data-stop-timer>结束计时</button></div>`;
   const paint=(el,active)=>{if(!el)return;if(!active){if(el.firstChild)el.replaceChildren();delete el.dataset.timerToken;return;}if(el.dataset.timerToken===timer.token&&el.querySelector('.timer-dock')){el.querySelector('strong').textContent=clock;el.querySelector('small').textContent=status;}else{el.innerHTML=html;el.dataset.timerToken=timer.token;}};
   paint(dock,true);paint(global,!detail);
 }
 window.nativeResume=()=>{applyTheme();updateTimer();if($('#settings-dialog').open)settingsRender();};
 function changePage(){listingLimit=36;const hash=location.hash.slice(1);page=['home','recipes','favorites','shopping'].includes(hash)?hash:'home';if($('#recipe-dialog').open)$('#recipe-dialog').close();detail=null;cooking=false;locked=false;landscape=false;if(native)native.cooking(false);render();updateTimer();window.scrollTo(0,0);}
 document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(a&&/^https?:/i.test(a.getAttribute('href'))&&native?.openExternal){e.preventDefault();native.openExternal(a.href,linkMode==='choose');return;}const b=e.target.closest('button');if(!b)return;
  if(locked&&!b.hasAttribute('data-unlock'))return;
  if(b.hasAttribute('data-unlock')){if(Date.now()-unlockAt<2000){locked=false;unlockAt=0;detailRender();}else{unlockAt=Date.now();b.textContent='再点一次解锁';}return;}
  if(b.hasAttribute('data-lock')){locked=true;unlockAt=0;detailRender();return;}
  if(b.hasAttribute('data-landscape')){landscape=!landscape;native?.landscape(landscape);detailRender();return;}
  if(b.hasAttribute('data-browse')){resetDiscovery();if(page==='recipes')render();else location.hash='recipes';return;}
  if(b.hasAttribute('data-request-open')){requestDraft={name:query.trim().slice(0,40),note:''};requestsRender();showDialog($('#requests-dialog'));$('#request-name').focus();return;}
  if(b.hasAttribute('data-request-save')){saveRequest();return;}
  if(b.dataset.requestRemove!==undefined){const index=Number(b.dataset.requestRemove);if(!requests[index]||!confirm('删除这条本机补菜建议？已经在 GitHub 提交的内容不受影响。'))return;const next=requests.filter((_,i)=>i!==index);if(write('requests',next)){requests=next;requestsRender();toast('本机建议已删除');}return;}
  if(b.dataset.requestCopy!==undefined){const r=requests[Number(b.dataset.requestCopy)];if(r)copyShopping(C.requestText(r),'补菜建议');return;}
  if(b.hasAttribute('data-relax-time')){max=0;persist();render();return;}
  if(b.hasAttribute('data-clear-discovery')){query='';cuisine='';group='';difficulty=0;persist();render();return;}
  if(b.hasAttribute('data-copy-shopping')||b.hasAttribute('data-share-shopping')){takeShopping(b.hasAttribute('data-share-shopping'));return;}
  if(b.hasAttribute('data-dismiss-timer-hint')){$('#timer-permission-dialog').close();return;}
  if(b.hasAttribute('data-timer-settings')){$('#timer-permission-dialog').close();settingsRender();showDialog($('#settings-dialog'));return;}
  if(b.hasAttribute('data-notifications')){native?.notificationSettings();return;}
  if(b.hasAttribute('data-exact')){native?.exactSettings();return;}
  if(b.hasAttribute('data-export')){exportBackup();return;}
  if(b.hasAttribute('data-import')){if(native)native.importBackup();else $('#backup-file').click();return;}
  if(b.hasAttribute('data-clear-history')){if(confirm('清空做菜记录？收藏和买菜清单不受影响。')){history=[];write('history',history);settingsRender();render();}return;}
  if(b.dataset.record){const stored=recordCooked(b.dataset.record);detailRender();toast(stored?'已记下今天做过':storageError);return;}
  if(b.hasAttribute('data-finish-recipe')){finishRecipe();return;}
  if(b.hasAttribute('data-journal-save')){const text=$('#recipe-note').value.trim();if(text)notes[detail.id]={text,updatedAt:Date.now()};else delete notes[detail.id];if(write('notes',notes))toast('笔记已保存');return;}
  if(b.dataset.historyOpen){$('#settings-dialog').close();detail=R.find(r=>r.id===b.dataset.historyOpen);cookIndex=progress[detail.id]?.index||0;cooking=false;detailRender();showDialog($('#recipe-dialog'));return;}
  if(b.dataset.systemTimer!==undefined){const step=detail.steps[Number(b.dataset.systemTimer)];if(timer&&!confirm('系统时钟中的计时需在时钟里结束。取消应用内当前计时，再在系统时钟设置本步骤？'))return;if(timer){native?.cancelTimer();timer=null;write('timer',null);updateTimer();}native?.systemTimer(step.seconds,detail.name+' · '+step.title);return;}
  if(b.hasAttribute('data-reset-filters')||b.hasAttribute('data-show-all-saved')){resetDiscovery();render();return;}
  if(b.hasAttribute('data-more')){const previous=listingLimit;listingLimit+=36;$('#list-results').innerHTML=listingResults();$('#list-results .recipe-card:nth-child('+(previous+1)+') .card-open')?.focus({preventScroll:true});return;}
  if(b.dataset.cuisine!==undefined){cuisine=b.dataset.cuisine;persist();render();return;}
  if(b.hasAttribute('data-draw')){const redraw=b.hasAttribute('data-redraw');selected=C.choose(pool(),[...history.filter(h=>h.at>Date.now()-7*86400000).map(h=>h.id),...recent],Math.random,R);if(selected){selectedCriteria=criteria();recent=[...recent,selected.id].slice(-10);write('recent',recent);}if(page==='home'){updateList();$('#random-result').scrollIntoView({behavior:'smooth',block:'nearest'});(redraw?$('#random-result [data-redraw]'):$('#drawn-title'))?.focus({preventScroll:true});}return;}
  if(b.dataset.difficulty!==undefined){difficulty=Number(b.dataset.difficulty);persist();render();return;}
  if(b.dataset.category!==undefined){group='';cuisine='';category=b.dataset.category;persist();render();return;}
  if(b.dataset.open){detail=R.find(r=>r.id===b.dataset.open);cookIndex=progress[detail.id]?.index||0;cooking=false;detailRender();showDialog($('#recipe-dialog'));$('#recipe-dialog').scrollTop=0;return;}
  if(b.dataset.save){const id=b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];const stored=write('saved',saved);if(detail)detailRender();else render();toast(stored?(saved.includes(id)?'已收藏，下次还做这道':'已取消收藏'):storageError);return;}
  if(b.dataset.portions){const before=C.shopping(R,basket,portions);portions=Math.max(1,Math.min(6,portions+Number(b.dataset.portions)));preserveBought(before);persist(false);if(detail)detailRender();else render();return;}
  if(b.hasAttribute('data-close')){closeDetail();return;}
  if(b.dataset.add){let changed=false,stored=true;if(!basket.includes(b.dataset.add)){const before=C.shopping(R,basket,portions);basket.push(b.dataset.add);changed=before.some(i=>bought[i.key]&&C.shopping(R,basket,portions).find(n=>n.key===i.key)?.amount>i.amount);preserveBought(before);stored=write('basket',basket);}detailRender();toast(stored?(changed?'已加入清单；增加用量的食材需重新核对，其余勾选保留':'已加入买菜清单'):storageError);return;}
  if(b.dataset.remove){const before=C.shopping(R,basket,portions);basket=basket.filter(id=>id!==b.dataset.remove);preserveBought(before);write('basket',basket);render();return;}
  if(b.hasAttribute('data-restart')){if(confirm('清除此菜的步骤记录，从第一步重新开始？')){clearProgress(detail.id);cookIndex=0;detailRender();}return;}
  if(b.hasAttribute('data-cook')){cooking=true;locked=false;lastNext=0;cookIndex=progress[detail.id]?.index||0;saveProgress();detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.hasAttribute('data-prev')){cookIndex=Math.max(0,cookIndex-1);saveProgress();detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.hasAttribute('data-next')){if(Date.now()-lastNext<600)return;lastNext=Date.now();done[detail.id+'-'+cookIndex]=true;if(cookIndex===detail.steps.length-1){finishRecipe();return;}else {cookIndex++;saveProgress();}detailRender();$('#recipe-dialog').scrollTop=0;return;}
  if(b.dataset.timer!==undefined){const s=detail.steps[Number(b.dataset.timer)];if(timer&&timer.end>Date.now()&&!confirm('已有一个计时正在进行。结束它并开始新计时？'))return;const token=Date.now()+'-'+detail.id;const mode=native?native.startTimer(s.seconds,detail.name+' · '+s.title,token):'foreground';timer={recipe:detail.id,title:s.title,end:Date.now()+s.seconds*1000,notified:false,token,mode};write('timer',timer);try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}updateTimer();toast(timer.mode==='native'?'已安排系统提醒，请确认音量及勿扰设置':'当前仅前台提醒；在设置中开启后台提醒，或使用系统时钟');showTimerHint();return;}
  if(b.hasAttribute('data-stop-timer')){native?.cancelTimer();timer=null;write('timer',null);updateTimer();return;}
 });
 document.addEventListener('keydown',e=>{if(e.target.id==='request-name'&&e.key==='Enter'&&!e.isComposing){e.preventDefault();saveRequest();}});
 document.addEventListener('input',e=>{if(e.target.id==='request-name')requestDraft.name=e.target.value;if(e.target.id==='request-note')requestDraft.note=e.target.value;if(e.target.id==='recipe-note'&&detail)noteDrafts[detail.id]=e.target.value;if(e.target.id==='search'){query=e.target.value;persist();updateList();}if(e.target.id==='exclude'){exclude=e.target.value;persist();updateList();}});
 document.addEventListener('change',e=>{if(e.target.id==='shopping-pending'){shoppingPendingOnly=e.target.checked;}if(e.target.id==='link-mode'){linkMode=e.target.value==='default'?'default':'choose';write('linkMode',linkMode);}if(e.target.id==='theme'){theme=e.target.value;write('theme',theme);applyTheme();}if(e.target.id==='cuisine'){cuisine=e.target.value;persist();updateList();}if(e.target.id==='food-group'){group=e.target.value;persist();updateList();}if(e.target.id==='no-noodles'){noNoodles=e.target.checked;persist();updateList();}if(e.target.id==='max'){max=Number(e.target.value);persist();updateList();}if(e.target.id==='no-spicy'){noSpicy=e.target.checked;persist();updateList();}if(e.target.dataset.bought){bought[e.target.dataset.bought]=e.target.checked;write('bought',bought);e.target.closest('label').classList.toggle('checked',e.target.checked);changedIngredients.delete(e.target.dataset.bought);e.target.closest('label').classList.remove('amount-changed');e.target.closest('label').querySelector('small')?.remove();const list=C.shoppingItems(R,basket,portions),pending=list.filter(i=>!bought[i.key]).length;$('#shopping-count').textContent='待买 '+pending+' 项 · 已买 '+(list.length-pending)+' 项';}if(e.target.dataset.done!==undefined){done[detail.id+'-'+e.target.dataset.done]=e.target.checked;cookIndex=C.firstUnchecked(detail.steps.map((_,i)=>i).filter(i=>done[detail.id+'-'+i]),detail.steps.length);saveProgress();const top=$('#recipe-dialog').scrollTop;detailRender();$('#recipe-dialog').scrollTop=top;}});
 document.addEventListener('toggle',e=>{if(e.target.classList?.contains('advanced-filters'))advancedOpen=e.target.open;if(e.target.dataset?.tutorial){if(e.target.open)tutorialOpen.add(e.target.dataset.tutorial);else tutorialOpen.delete(e.target.dataset.tutorial);}},true);
 $('#close-requests').onclick=()=>$('#requests-dialog').close();
 $('#close-shopping-export').onclick=()=>$('#shopping-export-dialog').close();
 $('#settings').onclick=()=>{settingsRender();showDialog($('#settings-dialog'));};
 $('#close-settings').onclick=()=>$('#settings-dialog').close();
 $('#backup-file').onchange=async e=>{const file=e.target.files[0];if(file){if(file.size>1000000)toast('文件过大，未导入');else try{window.receiveBackup(await file.text());}catch{toast('无法读取备份');}}e.target.value='';};
 $('#recipe-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
 $('#help').onclick=()=>showDialog($('#guide-dialog'));$('#close-guide').onclick=()=>$('#guide-dialog').close();
 window.appBack=()=>{const dlg=topDialog();if(dlg){if(dlg.id==='recipe-dialog')closeDetail();else dlg.close();return true;}if(page!=='home'){location.hash='home';return true;}return false;};
 window.matchMedia?.('(prefers-color-scheme: dark)').addEventListener('change',applyTheme);window.addEventListener('hashchange',changePage);document.addEventListener('visibilitychange',updateTimer);setInterval(updateTimer,1000);applyTheme();changePage();updateTimer();if(!migration.writable)toast(migration.reason);else if(migration.resetProgressIds?.length)toast('部分步骤记录已过期，请重新核对食材。收藏与笔记已保留。');
})();
